rog_map:
  resolution: 0.1
  inflation_resolution: 0.2
  inflation_step: 2
  unk_inflation_en: false
  unk_inflation_step: 1
  map_size: [ 50,50,6 ]
  # If the map rolling is disable, the map origin [m] should be set.
  fix_map_origin: [ 0,0,1.5 ]
  frontier_extraction_en: false

  # Virtual ceil and ground
  virtual_ceil_height: 3.5
  virtual_ground_height: -0.1

  load_pcd_en: false

  map_sliding:
    enable: true
    # The minimum distance [m] to slide the map.
    threshold: 0.3

  esdf:
    enable: false
    resolution: 0.1
    # The range of esdf around the odom [m].
    local_update_box: [ 5,5,3 ]

  projection:
    enable: false
    scan_z_min_rel: -0.05
    can_z_max_rel: 0.60
    max_distance: 6.0
    min_distance: -3.0
    clamp_distance: true
    projection.inflation_radius: 0.0 #冗余，故暂时弃用




  # If [enable = true], the ROG-Map will actively take ros topic as input.
  #  else user should call function [updateMap] to update the map.
  ros_callback:
    enable: true
    cloud_topic: "/cloud_registered"
    odom_topic: "/lidar_slam/odom"
    odom_timeout: 2.0